name: gdal_python36
channels:
  - conda-forge/label/gcc7
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - altair=2.2.2=py_0
  - asn1crypto=0.24.0=py_1
  - atk=2.25.90=hf2eb9ee_1001
  - attrs=18.2.0=py_0
  - blas=1.0=mkl
  - boost-cpp=1.68.0=h11c811c_1000
  - branca=0.3.0=py_0
  - brotlipy=0.7.0=py36h14c3975_1000
  - bzip2=1.0.6=h14c3975_1002
  - ca-certificates=2020.6.24=0
  - cairo=1.14.12=h7636065_2
  - certifi=2020.6.20=py36_0
  - cffi=1.11.5=py36h9745a5d_1001
  - chardet=3.0.4=py_1
  - click=7.0=py_0
  - click-plugins=1.0.4=py_0
  - cligj=0.5.0=py36_0
  - cryptography=2.3.1=py36hb7f436b_1000
  - curl=7.63.0=h646f8bb_1000
  - cycler=0.10.0=py_1
  - dbus=1.13.0=h4e0c4b3_1000
  - descartes=1.1.0=py_2
  - entrypoints=0.3=py36_0
  - expat=2.2.5=hf484d3e_1002
  - fiona=1.7.10=py36h48a52f0_0
  - folium=0.6.0=py_0
  - fontconfig=2.12.6=h49f89f6_0
  - freetype=2.8=hab7d2ae_1
  - freexl=1.0.5=h14c3975_1002
  - fribidi=1.0.10=h7b6447c_0
  - gdal=2.2.2=py36hc209d97_1
  - gdk-pixbuf=2.36.12=h4f1c04b_1001
  - geographiclib=1.49=py_0
  - geopandas=0.6.1=py_0
  - geopy=1.17.0=py_0
  - geos=3.6.2=heeff764_2
  - geotiff=1.4.2=h8e81d37_0
  - gettext=0.19.8.1=h9745a5d_1001
  - giflib=5.1.4=h14c3975_1001
  - glib=2.56.2=had28632_1001
  - gobject-introspection=1.56.1=py36h9e29830_1001
  - graphite2=1.3.13=hf484d3e_1000
  - gst-plugins-base=1.12.5=h3865690_1000
  - gstreamer=1.12.5=h0cc0488_1000
  - harfbuzz=1.7.6=h5f0a787_1
  - hdf4=4.2.13=h9a582f1_1002
  - hdf5=1.10.1=h9caa474_1
  - icu=58.2=hf484d3e_1000
  - idna=2.7=py_1
  - importlib-metadata=1.7.0=py36_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2020.1=217
  - ipython=7.16.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - jinja2=2.10=py_1
  - jpeg=9c=h14c3975_1001
  - json-c=0.12.1=ha6a3662_2
  - jsonschema=3.2.0=py36_0
  - kealib=1.4.7=h79811e5_5
  - kiwisolver=1.0.1=py36h6bb024c_1002
  - krb5=1.16.3=hc83ff2d_1000
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcurl=7.63.0=h01ee5af_1000
  - libdap4=3.19.1=hd48c02d_1000
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.2.1=hf484d3e_1005
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgdal=2.2.2=h804cdde_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h14c3975_1004
  - libkml=1.3.0=h328b03d_1009
  - libnetcdf=4.4.1.1=h816af47_8
  - libpng=1.6.36=h84994c4_1000
  - libpq=10.6=h13b8bad_1000
  - libspatialindex=1.8.5=hf484d3e_1003
  - libspatialite=4.3.0a=h72746d6_18
  - libssh2=1.8.0=h1ad7b7a_1003
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h648cc4a_1001
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.8=h143f9aa_1005
  - markupsafe=1.1.0=py36h14c3975_1000
  - matplotlib=2.2.2=py36h0e671d2_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.1.0=py36h23d657b_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - munch=2.3.2=py_0
  - ncurses=6.2=he6710b0_1
  - networkx=2.2=py_1
  - numpy=1.19.1=py36hbc911f0_0
  - numpy-base=1.19.1=py36hfa32c7d_0
  - openjpeg=2.3.0=hf38bd82_1003
  - openssl=1.0.2u=h7b6447c_0
  - osmnx=0.8.2=py_0
  - pandas=0.24.0rc1=py36hf484d3e_0
  - pango=1.42.0=h377f3fa_0
  - pcre=8.41=hf484d3e_1003
  - pexpect=4.8.0=py36_0
  - pip=20.2.2=py36_0
  - pixman=0.34.0=h14c3975_1003
  - poppler=0.60.1=hc909a00_0
  - poppler-data=0.4.9=0
  - postgresql=10.6=h66cca7a_1000
  - proj4=4.9.3=hc8507d1_7
  - pthread-stubs=0.4=h14c3975_1001
  - pycparser=2.19=py_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.2.1=py_0
  - pyproj=1.9.5.1=py36_0
  - pyqt=5.6.0=py36h13b7fb3_1008
  - pyrsistent=0.14.9=py36h14c3975_1000
  - pysocks=1.7.1=py36_0
  - python=3.6.6=hd21baee_1003
  - pytz=2018.5=py_0
  - qt=5.6.2=hd25b39d_14
  - readline=7.0=h7b6447c_5
  - requests=2.24.0=py_0
  - rtree=0.8.3=py36_0
  - setuptools=49.6.0=py36_0
  - shapely=1.6.4=py36h7ef4460_0
  - sip=4.18.1=py36hf484d3e_1000
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.9.0=py_1
  - traitlets=4.3.3=py36_0
  - typing=3.7.4.3=py36_0
  - tzcode=2018g=h14c3975_1001
  - urllib3=1.25.10=py_0
  - vincent=0.4.4=py_1
  - wheel=0.34.2=py36_0
  - xerces-c=3.2.2=hac72e42_1001
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.9=h14c3975_1004
  - xorg-libsm=1.2.3=h4937e3b_1000
  - xorg-libx11=1.6.6=h14c3975_1000
  - xorg-libxau=1.0.8=h14c3975_1006
  - xorg-libxdmcp=1.1.2=h14c3975_1007
  - xorg-libxext=1.3.3=h14c3975_1004
  - xorg-libxrender=0.9.10=h14c3975_1002
  - xorg-libxt=1.1.5=h14c3975_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - backcall==0.2.0
    - boto3==1.14.47
    - botocore==1.17.47
    - decorator==4.4.2
    - docutils==0.15.2
    - google-pasta==0.2.0
    - ipykernel==5.3.4
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - jmespath==0.10.0
    - joblib==0.16.0
    - jupyter-client==6.1.6
    - jupyter-core==4.6.3
    - mxnet==1.7.0.post1
    - opencv-python==4.4.0.42
    - packaging==20.4
    - parso==0.7.1
    - pickleshare==0.7.5
    - pillow==7.2.0
    - prompt-toolkit==3.0.6
    - protobuf==3.13.0
    - protobuf3-to-dict==0.1.5
    - ptyprocess==0.6.0
    - pygments==2.6.1
    - python-dateutil==2.8.1
    - pyzmq==19.0.2
    - s3transfer==0.3.3
    - sagemaker==1.72.0
    - scikit-learn==0.23.2
    - scipy==1.5.2
    - sklearn==0.0
    - smdebug-rulesconfig==0.1.4
    - threadpoolctl==2.1.0
    - tornado==6.0.4
    - wcwidth==0.2.5
prefix: /home/ec2-user/SageMaker/custom-miniconda/miniconda/envs/gdal_python36

